/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mychatappp;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import mychatappp.gui.MainScreen;

/**
 *
 * @author Stranger SSC
 */
public class SignUp extends javax.swing.JFrame {

    String ch ;

    public JTextField getTextName() {
        return textName;
    }
     Connection conn= null;
    PreparedStatement pst= null;
    ResultSet rs= null;
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        Email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Too Me");
        setMinimumSize(new java.awt.Dimension(900, 450));
        setPreferredSize(new java.awt.Dimension(900, 450));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Facebook Letter Faces", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 40, 90, 50);

        jLabel1.setFont(new java.awt.Font("Facebook Letter Faces", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PassWord :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(75, 158, 128, 24);

        jLabel3.setFont(new java.awt.Font("Facebook Letter Faces", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E_mail :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(75, 275, 91, 24);
        getContentPane().add(textName);
        textName.setBounds(330, 50, 400, 30);

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass);
        txtPass.setBounds(330, 160, 400, 30);
        getContentPane().add(Email);
        Email.setBounds(330, 280, 400, 30);

        jButton1.setText("SignUp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 370, 290, 26);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mychatappp/back.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 900, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ch=Email.getText();
        
         conn=MySqlConnect.ConnectBD();

         String Sql="insert into user (username,password) values (?,?)   ";
         //String Sql="Update user set username='"+textName.getText()+"' , password='"+txtPass.getText()+"' where username='"+textName.getText()+"' ";
         
         try{

            pst=conn.prepareStatement(Sql);
            pst.setString(1,textName.getText());
            pst.setString(2,txtPass.getText());
            
            if((ch.indexOf("@")> -1)||(textName.getText().indexOf("")<-1)||(txtPass.getText().indexOf("")<-1)){
             pst.execute();

           JOptionPane.showMessageDialog(null," Data saved ");

               
                SignIn IN = new SignIn();

               IN.setVisible(true);

            
                pst.close();
            }
            else {
               JOptionPane.showMessageDialog(null," PROBLEM IN NAME OR PASSWORD OR E_MAIL  ","access denied",JOptionPane.ERROR_MESSAGE);
}

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }

         
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
        
       
    }
 private void setIcon() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("unnamed.png")));    
 }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textName;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
